# SPDX-License-Identifier: Apache-2.0

config:
  line-length: false
  no-emphasis-as-header: false
  no-emphasis-as-heading: false
  first-line-heading: false
  code-block-style: false
  no-duplicate-header: false
  single-trailing-newline: false
globs:
  - "**/*.md"
ignores:
  - ".github/**"
  - ".tox/**"
  - "venv/**"
  - ".venv/**"
